use serde::{Deserialize, Serialize};

use super::proof_compression::{CompressedBalanceProof, CompressedSpentProof};

/// Proof set generated by the sender for updating the sender's balance proof.
/// This is common in batch transfers, hence it is extracted into a separate structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SenderProofSet {
    pub spent_proof: CompressedSpentProof,
    pub prev_balance_proof: CompressedBalanceProof,
}
