/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_key_free(a: number, b: number): void;
export function __wbg_get_key_privkey(a: number): Array;
export function __wbg_set_key_privkey(a: number, b: number, c: number): void;
export function __wbg_get_key_pubkey(a: number): Array;
export function __wbg_set_key_pubkey(a: number, b: number, c: number): void;
export function __wbg_txrequestresult_free(a: number, b: number): void;
export function __wbg_get_txrequestresult_tx(a: number): number;
export function __wbg_set_txrequestresult_tx(a: number, b: number): void;
export function __wbg_get_txrequestresult_memo(a: number): number;
export function __wbg_set_txrequestresult_memo(a: number, b: number): void;
export function generate_key_from_provisional(a: number, b: number): number;
export function prepare_deposit(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function send_tx_request(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function query_proposal(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function finalize_tx(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function sync(a: number, b: number, c: number): number;
export function sync_withdrawals(a: number, b: number, c: number): number;
export function get_user_data(a: number, b: number, c: number): number;
export function decrypt_deposit_data(a: number, b: number, c: number, d: number): number;
export function decrypt_transfer_data(a: number, b: number, c: number, d: number): number;
export function decrypt_tx_data(a: number, b: number, c: number, d: number): number;
export function mimic_deposit(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_jsgenericaddress_free(a: number, b: number): void;
export function __wbg_get_jsgenericaddress_is_pubkey(a: number): number;
export function __wbg_set_jsgenericaddress_is_pubkey(a: number, b: number): void;
export function jsgenericaddress_new(a: number, b: number, c: number): number;
export function __wbg_jstransfer_free(a: number, b: number): void;
export function __wbg_get_jstransfer_recipient(a: number): number;
export function __wbg_set_jstransfer_recipient(a: number, b: number): void;
export function __wbg_get_jstransfer_token_index(a: number): number;
export function __wbg_set_jstransfer_token_index(a: number, b: number): void;
export function __wbg_get_jstransfer_amount(a: number): Array;
export function __wbg_set_jstransfer_amount(a: number, b: number, c: number): void;
export function __wbg_get_jstransfer_salt(a: number): Array;
export function __wbg_set_jstransfer_salt(a: number, b: number, c: number): void;
export function jstransfer_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function __wbg_get_jstx_nonce(a: number): number;
export function __wbg_set_jstx_nonce(a: number, b: number): void;
export function __wbg_jsdepositdata_free(a: number, b: number): void;
export function __wbg_get_jsdepositdata_deposit_salt(a: number): Array;
export function __wbg_set_jsdepositdata_deposit_salt(a: number, b: number, c: number): void;
export function __wbg_get_jsdepositdata_pubkey_salt_hash(a: number): Array;
export function __wbg_set_jsdepositdata_pubkey_salt_hash(a: number, b: number, c: number): void;
export function __wbg_get_jsdepositdata_token_index(a: number): number;
export function __wbg_set_jsdepositdata_token_index(a: number, b: number): void;
export function __wbg_get_jsdepositdata_amount(a: number): Array;
export function __wbg_set_jsdepositdata_amount(a: number, b: number, c: number): void;
export function __wbg_jstransferdata_free(a: number, b: number): void;
export function __wbg_get_jstransferdata_transfer(a: number): number;
export function __wbg_set_jstransferdata_transfer(a: number, b: number): void;
export function __wbg_jstxdata_free(a: number, b: number): void;
export function __wbg_get_jstxdata_tx(a: number): number;
export function __wbg_get_jstxdata_transfers(a: number): Array;
export function __wbg_set_jstxdata_transfers(a: number, b: number, c: number): void;
export function __wbg_jsuserdata_free(a: number, b: number): void;
export function __wbg_get_jsuserdata_pubkey(a: number): Array;
export function __wbg_set_jsuserdata_pubkey(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_block_number(a: number): number;
export function __wbg_set_jsuserdata_block_number(a: number, b: number): void;
export function __wbg_get_jsuserdata_balances(a: number): Array;
export function __wbg_set_jsuserdata_balances(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_private_commitment(a: number): Array;
export function __wbg_set_jsuserdata_private_commitment(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_deposit_lpt(a: number): number;
export function __wbg_set_jsuserdata_deposit_lpt(a: number, b: number): void;
export function __wbg_get_jsuserdata_transfer_lpt(a: number): number;
export function __wbg_set_jsuserdata_transfer_lpt(a: number, b: number): void;
export function __wbg_get_jsuserdata_tx_lpt(a: number): number;
export function __wbg_set_jsuserdata_tx_lpt(a: number, b: number): void;
export function __wbg_get_jsuserdata_withdrawal_lpt(a: number): number;
export function __wbg_set_jsuserdata_withdrawal_lpt(a: number, b: number): void;
export function __wbg_get_jsuserdata_processed_deposit_uuids(a: number): Array;
export function __wbg_set_jsuserdata_processed_deposit_uuids(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_processed_transfer_uuids(a: number): Array;
export function __wbg_set_jsuserdata_processed_transfer_uuids(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_processed_tx_uuids(a: number): Array;
export function __wbg_set_jsuserdata_processed_tx_uuids(a: number, b: number, c: number): void;
export function __wbg_get_jsuserdata_processed_withdrawal_uuids(a: number): Array;
export function __wbg_set_jsuserdata_processed_withdrawal_uuids(a: number, b: number, c: number): void;
export function __wbg_tokenbalance_free(a: number, b: number): void;
export function __wbg_get_tokenbalance_is_insufficient(a: number): number;
export function __wbg_set_tokenbalance_is_insufficient(a: number, b: number): void;
export function __wbg_jstx_free(a: number, b: number): void;
export function __wbg_get_tokenbalance_token_index(a: number): number;
export function __wbg_set_jstx_transfer_tree_root(a: number, b: number, c: number): void;
export function __wbg_set_jsgenericaddress_data(a: number, b: number, c: number): void;
export function __wbg_set_jstransferdata_sender(a: number, b: number, c: number): void;
export function __wbg_set_tokenbalance_amount(a: number, b: number, c: number): void;
export function __wbg_set_jstxdata_tx(a: number, b: number): void;
export function __wbg_set_tokenbalance_token_index(a: number, b: number): void;
export function __wbg_get_jstx_transfer_tree_root(a: number): Array;
export function __wbg_get_jsgenericaddress_data(a: number): Array;
export function __wbg_get_jstransferdata_sender(a: number): Array;
export function __wbg_get_tokenbalance_amount(a: number): Array;
export function __wbg_config_free(a: number, b: number): void;
export function __wbg_get_config_store_vault_server_url(a: number): Array;
export function __wbg_set_config_store_vault_server_url(a: number, b: number, c: number): void;
export function __wbg_get_config_block_validity_prover_url(a: number): Array;
export function __wbg_set_config_block_validity_prover_url(a: number, b: number, c: number): void;
export function __wbg_get_config_balance_prover_url(a: number): Array;
export function __wbg_set_config_balance_prover_url(a: number, b: number, c: number): void;
export function __wbg_get_config_withdrawal_aggregator_url(a: number): Array;
export function __wbg_set_config_withdrawal_aggregator_url(a: number, b: number, c: number): void;
export function __wbg_get_config_deposit_timeout(a: number): number;
export function __wbg_set_config_deposit_timeout(a: number, b: number): void;
export function __wbg_get_config_tx_timeout(a: number): number;
export function __wbg_set_config_tx_timeout(a: number, b: number): void;
export function config_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_export_3: WebAssembly.Table;
export function closure533_externref_shim(a: number, b: number, c: number): void;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __externref_table_alloc(): number;
export function __externref_drop_slice(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function closure650_externref_shim(a: number, b: number, c: number, d: number): void;
export function __wbindgen_start(): void;
